kind: Service
apiVersion: v1
metadata:
  name: demo-quarkus
  labels:
    app: demo-quarkus
spec:
  ports:
    - name: http-port
      protocol: TCP
      port: {{ .Values.application.service.port }}
      targetPort: {{ .Values.application.pod.port }}
  selector:
    app: demo-quarkus
  type: ClusterIP