apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-quarkus
spec:
  rules:
    - http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: demo-quarkus
                port:
                  number: {{ .Values.application.service.port }}
      host: {{ .Values.ingress.host }}