apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: otel-collector
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      component: otel-collector
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: otel-collector
    spec:
      containers:
        - args:
            - --config=/conf/otel-collector-config.yaml
            - --log-level=DEBUG
          image: otel/opentelemetry-collector:latest
          name: otel-collector
          ports:
            - containerPort: 1888
            - containerPort: 8888
            - containerPort: 8889
            - containerPort: 13133
            - containerPort: 4317
            - containerPort: 55679
          resources: {}
          volumeMounts:
          - mountPath: /conf
            name: otel-collector-config-volume
      restartPolicy: Always
      volumes:
         - name: otel-collector-config-volume
           configMap:
             name: otel-collector
             items:
               - key: otel-collector-config
                 path: otel-collector-config.yaml

---

apiVersion: v1
kind: Service
metadata:
  labels:
    component: otel-collector
  name: otel-collector
spec:
  ports:
    - name: "1888"
      port: 1888
      targetPort: 1888
    - name: "8888"
      port: 8888
      targetPort: 8888
    - name: "8889"
      port: 8889
      targetPort: 8889
    - name: "13133"
      port: 13133
      targetPort: 13133
    - name: "4317"
      port: 4317
      targetPort: 4317
    - name: "55670"
      port: 55670
      targetPort: 55679
  selector:
    component: otel-collector
